version: "3.7"

services:
  redis:
    image: redis
    container_name: redis
    
    ports:
      - "6379:6379"
    volumes:
    - .docker/redis/redis.conf:/etc/redis/redis.conf
    command: ["redis-server", "/etc/redis/redis.conf"]

  app:
    container_name: app
    build:
      context: .
      dockerfile: ./docker/app/app.dockerfile

    ports:
      - "8000:8000"

    depends_on:
      - redis


  